import type { Tool } from './types';
import {
  ImageConverter,
  ImageCompressor,
  ImageCropper,
  VideoConverter,
  AudioConverter,
  AudioTrimmer,
  AgeCalculator,
  EmiCalculator,
  SipCalculator,
  QrCodeGenerator,
  PasswordGenerator,
  WordCounter,
  Base64EncoderDecoder,
  ColorPicker,
  TextToSpeech,
  SpeechToText,
  JsonFormatter,
  UnitConverter,
  BmiCalculator,
  TimerStopwatch,
  TextToVideoMaker,
  ColoringBookMaker,
  KiddoFunWorldStories,
} from './components/tools';

export const TOOLS: Tool[] = [
  {
    id: 'kiddo-fun-world-stories',
    title: 'Kiddo Fun World Stories',
    description: 'Generate magical, multi-page storybooks with AI illustrations.',
    component: KiddoFunWorldStories,
  },
  {
    id: 'image-converter',
    title: 'Image Converter',
    description: 'Convert between JPG, PNG, and WEBP formats using canvas.',
    component: ImageConverter,
  },
  {
    id: 'image-compressor',
    title: 'Image Compressor',
    description: 'Compress image file size with adjustable quality settings.',
    component: ImageCompressor,
  },
  {
    id: 'image-cropper',
    title: 'Image Cropper',
    description: 'Upload, crop with a live preview, and export your image.',
    component: ImageCropper,
  },
  {
    id: 'video-converter',
    title: 'Video Converter',
    description: 'Convert video files to the WebM format directly in your browser.',
    component: VideoConverter,
  },
    {
    id: 'text-to-video-maker',
    title: 'Text to Video Maker',
    description: 'Generate a short video from a text prompt using AI.',
    component: TextToVideoMaker,
  },
  {
    id: 'coloring-book-maker',
    title: 'AI Coloring Book Generator',
    description: 'Generate a 20-page PDF coloring book with varied artistic styles from a single prompt.',
    component: ColoringBookMaker,
  },
  {
    id: 'audio-converter',
    title: 'Audio Converter',
    description: 'Convert audio files to WAV format using the Web Audio API.',
    component: AudioConverter,
  },
  {
    id: 'audio-trimmer',
    title: 'Audio Trimmer',
    description: 'Trim audio clips by specifying start and end times.',
    component: AudioTrimmer,
  },
  {
    id: 'age-calculator',
    title: 'Age Calculator',
    description: 'Calculate age in years, months, and days from a birth date.',
    component: AgeCalculator,
  },
  {
    id: 'emi-calculator',
    title: 'EMI Calculator',
    description: 'Calculate Equated Monthly Installment for loans.',
    component: EmiCalculator,
  },
  {
    id: 'sip-calculator',
    title: 'SIP Calculator',
    description: 'Calculate the future value of your monthly investments.',
    component: SipCalculator,
  },
  {
    id: 'qr-code-generator',
    title: 'QR Code Generator',
    description: 'Generate and download a QR code for any text or URL.',
    component: QrCodeGenerator,
  },
  {
    id: 'password-generator',
    title: 'Password Generator',
    description: 'Create secure passwords with customizable options.',
    component: PasswordGenerator,
  },
  {
    id: 'word-counter',
    title: 'Word Counter',
    description: 'Count words, characters, and estimate reading time.',
    component: WordCounter,
  },
  {
    id: 'base64-encoder-decoder',
    title: 'Base64 Encoder/Decoder',
    description: 'Encode to and decode from Base64 format.',
    component: Base64EncoderDecoder,
  },
  {
    id: 'color-picker',
    title: 'Color Picker',
    description: 'Pick a color and get its HEX, RGB, and HSL values.',
    component: ColorPicker,
  },
  {
    id: 'text-to-speech',
    title: 'Text to Speech',
    description: 'Convert text into spoken audio using browser APIs.',
    component: TextToSpeech,
  },
  {
    id: 'speech-to-text',
    title: 'Speech to Text',
    description: 'Convert your voice into text using the microphone.',
    component: SpeechToText,
  },
  {
    id: 'json-formatter',
    title: 'JSON Formatter',
    description: 'Format, validate, and beautify JSON data.',
    component: JsonFormatter,
  },
  {
    id: 'unit-converter',
    title: 'Unit Converter',
    description: 'Convert between various units of measurement.',
    component: UnitConverter,
  },
  {
    id: 'bmi-calculator',
    title: 'BMI Calculator',
    description: 'Calculate your Body Mass Index.',
    component: BmiCalculator,
  },
  {
    id: 'timer-stopwatch',
    title: 'Timer / Stopwatch',
    description: 'A simple tool for timing events.',
    component: TimerStopwatch,
  },
];